server:
  port: 443
  ssl:
    enabled: true
    key-store: "classpath:bootsecurity.p12"
    key-store-password: '00000000'
    key-store-type: PKCS12
    key-alias: bootsecurity

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lunch
    username: ${DATABASE_NAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${AUTH_CLIENT_ID}
            client-secret: ${AUTH_CLIENT_SECRET}
            redirect-uri: https://accounts.google.com/o/oauth2/v2/auth
            scope: profile, email
jwt:
  secret: ${JWT_SECRET}

lunchBackend:
  openapi:
    dev-url: "http://localhost:8080"
    prod-url: "https://api.myapp.com"

openai:
  model: gpt-3.5-turbo
  api:
    key: ${OPENAI_KEY}
    chat-url: https://api.openai.com/v1/chat/completions
    image-url: https://api.openai.com/v1/images/generations

