name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Spring App to EC2
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 3. Gradle 빌드
      - name: print
        run: ls build/libs

      # 5. EC2 서버로 파일 전송 (첫 번째 JAR 파일을 자동으로 선택)
      - name: Upload Jar to EC2
        run: |
          JAR_FILE=$(ls build/libs/*.jar | grep -v 'plain' | head -n 1)
          echo "Uploading $JAR_FILE to EC2"
          scp -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} "$JAR_FILE" ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/lunchBackend.jar

      # 5. EC2 서버에서 애플리케이션 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo 'here'
            pkill -f 'java -jar' || true
            echo 'here: 2'
            nohup java -jar /home/ubuntu/lunchBackend.jar > /home/ubuntu/app.log 2>&1 & disown
