name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Spring App to EC2
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 4. EC2 서버로 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            pkill -f 'java -jar' || true
            mv ~/app/lunchBackend.jar ~/app/lunchBackend-$(date +%F-%T).jar || true
            scp -o StrictHostKeyChecking=no build/libs/lunchBackend.jar ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/app/lunchBackend.jar
            nohup java -jar /home/ec2-user/app/lunchBackend.jar > /home/ec2-user/app/app.log 2>&1 &
