name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Spring App to EC2
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      # 3. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 5. EC2 서버에서 애플리케이션 실행
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            pkill -f 'java -jar' || true
            cd ~
            rm -rf cloud-1st-6Team-BE
            git clone https://github.com/woorifisa-service-dev-3rd/cloud-1st-6Team-BE.git
            cd cloud-1st-6Team-BE
            ./gradlew clean build -x test
            cd build/libs
            nohup java -jar lunchBackend-0.0.1-SNAPSHOT.jar > /home/ubuntu/lunchBackend.log 2>&1 &